#!/usr/bin/env python3
"""
Reassortment analysis for H9N2 Madagascar isolates.

For each H9N2 isolate present in the phylogenetic trees, we check whether its
8 genomic segments cluster within persistent Malagasy lineages (in-clade) or
represent recent introductions (singleton / absent).

Clade status per segment comes from results/clade_tips.tsv (generated by
analyse_trees.py --force). Isolate-level metadata comes from
data/combined_metadata.tsv, augmented by metadata extracted from tip names for
Norosoa (non-GISAID) sequences.

Tip name formats
----------------
  GISAID : EPI_SEG_ID|SEG|A/host/country/id/year|EPI_ISL_ID|subtype
  Norosoa: A/host/Madagascar/id/year_subtype_seg

For GISAID tips the isolate key is the EPI_ISL_ID (matches metadata).
For Norosoa tips the isolate key is "A/host/Madagascar/id/year" (the
base before the trailing _subtype_seg), which is consistent across all
eight segment trees for the same isolate.

Classification
--------------
Only segments with sequences in the trees are evaluated ("absent" = not
sequenced, does not imply recent importation).

  fully_local   – HA+NA in-clade; ≥5 total segments present, all in-clade
  largely_local – HA+NA in-clade; 2–4 segments present, all in-clade
  reassorted    – ≥1 present segment is singleton (present but NOT in any
                  Malagasy clade — phylogenetic signal of recent importation)
  all_singleton – no present segment in-clade

Outputs
-------
  results/reassortment_matrix.tsv  – one row per isolate, 8 status columns + class
  results/reassortment_summary.tsv – counts by Year × Host × classification
"""

import argparse
import sys
from pathlib import Path

import pandas as pd

# Map segment abbreviation → tree name in clade_tips.tsv
SEGMENT_TREES = {
    "HA":  "HA_H9N2",
    "NA":  "NA_H9N2",
    "PB2": "PB2",
    "PB1": "PB1",
    "PA":  "PA",
    "NP":  "NP",
    "MP":  "MP",
    "NS":  "NS",
}

SURFACE_SEGS  = ["HA", "NA"]
INTERNAL_SEGS = ["PB2", "PB1", "PA", "NP", "MP", "NS"]
ALL_SEGS      = SURFACE_SEGS + INTERNAL_SEGS


def norosoa_isolate_key(tip_name: str) -> str:
    """Extract A/host/Madagascar/id/year from a Norosoa tip name."""
    # Format: A/host/Madagascar/id/year_subtype_seg
    # Split on "_" and drop the last two tokens (subtype and segment).
    parts = tip_name.split("_")
    return "_".join(parts[:-2])


def norosoa_metadata(tip_name: str) -> dict:
    """Extract host, year, subtype from a Norosoa tip name."""
    # A/host/Madagascar/id/year_subtype_seg
    parts = tip_name.split("_")
    subtype  = parts[-2] if len(parts) >= 2 else ""
    # A/host/Madagascar/id/year — split by "/"
    base_parts = parts[0].split("/")
    host = base_parts[1] if len(base_parts) > 1 else ""
    year = base_parts[4] if len(base_parts) > 4 else ""
    return {"Host": host, "Year": year, "Subtype": subtype,
            "Country": "Madagascar", "Region": "", "Month": ""}


def classify(row) -> str:
    """Classify based only on present (non-absent) segments.

    'absent'    = segment not sequenced / not in tree → not informative.
    'singleton' = present but NOT in any Malagasy clade → reassortment signal.
    'clade'     = clusters within a persistent Malagasy lineage.
    """
    n_clade     = sum(row.get(s, "absent") == "clade"     for s in ALL_SEGS)
    n_singleton = sum(row.get(s, "absent") == "singleton" for s in ALL_SEGS)
    n_present   = n_clade + n_singleton

    if n_present == 0:
        return "all_absent"
    if n_singleton > 0:
        return "reassorted"     # phylogenetic evidence of segment importation
    if n_present >= 5:
        return "fully_local"    # ≥5 segments, all in-clade
    else:
        return "largely_local"  # ≥1 segment in-clade, limited coverage


def main():
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--tips",     default="results/clade_tips.tsv",
                        help="Tip assignment file (default: results/clade_tips.tsv)")
    parser.add_argument("--metadata", default="data/combined_metadata.tsv",
                        help="Isolate metadata (default: data/combined_metadata.tsv)")
    parser.add_argument("--out-dir",  default="results",
                        help="Output directory (default: results/)")
    parser.add_argument("--force",    action="store_true",
                        help="Overwrite existing output files")
    args = parser.parse_args()

    tips_path     = Path(args.tips)
    metadata_path = Path(args.metadata)
    out_dir       = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    matrix_path  = out_dir / "reassortment_matrix.tsv"
    summary_path = out_dir / "reassortment_summary.tsv"

    if not args.force:
        for p in [matrix_path, summary_path]:
            if p.exists():
                sys.exit(f"ERROR: {p} already exists. Use --force to overwrite.")

    # -------------------------------------------------------------------------
    # Load tip assignments
    # -------------------------------------------------------------------------
    print("Loading clade_tips.tsv ...")
    tips = pd.read_csv(tips_path, sep="\t", dtype=str)

    # Restrict to the 8 H9N2-relevant trees
    valid_trees = set(SEGMENT_TREES.values())
    tips = tips[tips["tree"].isin(valid_trees)].copy()

    # ---- Assign an isolate key for every tip --------------------------------
    # GISAID tips: use epi_isl_id already present in the file
    # Norosoa tips: derive key from tip_name (no "|" separator)
    is_gisaid = tips["epi_isl_id"].notna() & (tips["epi_isl_id"] != "")
    tips["isolate_key"] = tips["epi_isl_id"].where(
        is_gisaid,
        tips["tip_name"].apply(norosoa_isolate_key),
    )

    # Keep only H9N2 isolates:
    #   Norosoa – tip_name contains "_H9N2_"
    #   GISAID  – will be filtered to H9N2 keys after metadata load
    norosoa_h9n2 = tips[~is_gisaid & tips["tip_name"].str.contains("_H9N2_", na=False)].copy()
    gisaid_tips  = tips[is_gisaid].copy()

    # ---- Load H9N2 metadata --------------------------------------------------
    print("Loading metadata ...")
    meta_cols = [
        "Isolate_Id", "Subtype", "Host",
        "Collection_Date", "Year", "Month",
        "Country", "Region",
    ]
    meta = pd.read_csv(
        metadata_path, sep="\t", usecols=meta_cols, low_memory=False
    )
    h9n2_meta = meta[meta["Subtype"].str.contains("H9N2", na=False)].copy()
    h9n2_meta.rename(columns={"Isolate_Id": "isolate_key"}, inplace=True)
    # Which H9N2 isolates in the metadata also appear as tree tips?
    gisaid_tree_keys = set(gisaid_tips["isolate_key"].unique())
    gisaid_h9n2_meta = h9n2_meta[h9n2_meta["isolate_key"].isin(gisaid_tree_keys)].copy()
    # Filter GISAID tips to H9N2 keys only
    gisaid_h9n2_tips = gisaid_tips[
        gisaid_tips["isolate_key"].isin(set(gisaid_h9n2_meta["isolate_key"]))
    ].copy()
    print(f"  GISAID H9N2 in metadata with tree entry: {len(gisaid_h9n2_meta)}")

    # Build minimal metadata for Norosoa isolates from tip names
    norosoa_keys = norosoa_h9n2["isolate_key"].unique()
    norosoa_rows = []
    for key in norosoa_keys:
        # Find one representative tip name for this key to extract metadata
        rep_tip = norosoa_h9n2.loc[
            norosoa_h9n2["isolate_key"] == key, "tip_name"
        ].iloc[0]
        row = norosoa_metadata(rep_tip)
        row["isolate_key"] = key
        norosoa_rows.append(row)
    norosoa_meta = pd.DataFrame(norosoa_rows)
    print(f"  Norosoa H9N2 isolates in trees:          {len(norosoa_meta)}")

    # Combine
    META_COLS = ["isolate_key", "Subtype", "Host", "Year", "Month", "Country", "Region"]
    all_meta = pd.concat(
        [gisaid_h9n2_meta[META_COLS], norosoa_meta[META_COLS]],
        ignore_index=True,
    )

    # -------------------------------------------------------------------------
    # Build pivot: isolate_key × tree → in/out of clade
    # -------------------------------------------------------------------------
    all_h9n2_tips = pd.concat([gisaid_h9n2_tips, norosoa_h9n2], ignore_index=True)
    all_h9n2_tips["status"] = all_h9n2_tips["is_singleton"].map(
        {"True": "singleton", "False": "clade"}
    )

    tips_pivot = (
        all_h9n2_tips.groupby(["isolate_key", "tree"])["status"]
        .agg(lambda s: "clade" if "clade" in s.values else "singleton")
        .unstack(level="tree")
        .fillna("absent")
        .reset_index()
    )
    tree_to_seg = {v: k for k, v in SEGMENT_TREES.items()}
    tips_pivot.rename(columns=tree_to_seg, inplace=True)

    # -------------------------------------------------------------------------
    # Join metadata onto pivot
    # -------------------------------------------------------------------------
    matrix = all_meta.merge(tips_pivot, on="isolate_key", how="left")

    seg_cols = list(SEGMENT_TREES.keys())
    for seg in seg_cols:
        if seg not in matrix.columns:
            matrix[seg] = "absent"
        else:
            matrix[seg] = matrix[seg].fillna("absent")

    matrix["classification"] = matrix[seg_cols].apply(classify, axis=1)

    # -------------------------------------------------------------------------
    # Write outputs
    # -------------------------------------------------------------------------
    out_cols = (
        ["isolate_key", "Subtype", "Host", "Year", "Month", "Country", "Region"]
        + seg_cols
        + ["classification"]
    )
    matrix[out_cols].to_csv(matrix_path, sep="\t", index=False)

    meta_cols_grp = ["Year", "Host", "classification"]
    # Year may be NaN for some norosoa sequences — coerce to str for grouping
    matrix["Year"] = matrix["Year"].astype(str)
    summary = (
        matrix.groupby(meta_cols_grp, dropna=False)
        .size()
        .reset_index(name="n_isolates")
        .sort_values(["Year", "Host", "classification"])
    )
    summary.to_csv(summary_path, sep="\t", index=False)

    # -------------------------------------------------------------------------
    # Print overview
    # -------------------------------------------------------------------------
    n_with_any = (matrix[seg_cols].ne("absent").any(axis=1)).sum()
    print(f"\nTotal H9N2 isolates analysed:          {len(matrix)}")
    print(f"  with ≥1 segment in a tree:           {n_with_any}")
    print("\nClassification counts:")
    for cls, cnt in matrix["classification"].value_counts().items():
        print(f"  {cls:<20} {cnt:>4}")
    print("\nSegment-level clade/singleton/absent counts:")
    for seg in seg_cols:
        counts = matrix[seg].value_counts()
        print(f"  {seg:4s}: clade={counts.get('clade',0):3d}  "
              f"singleton={counts.get('singleton',0):3d}  "
              f"absent={counts.get('absent',0):3d}")

    print(f"\nResults written to:")
    print(f"  {matrix_path}")
    print(f"  {summary_path}")


if __name__ == "__main__":
    main()
